Feature: player mounts the board with his boats

  As a player
  I want to place my boats on a board
  So that I will be ready to begin a new match

  Scenario: mount the board
    Given I have a board with dimensions <width> x <height>
    And I have a set of boats for that board
    When I place each boat side by side from the biggest to the smallest, beginning from the top-left
    Then my private board should be: <matrix>
    And there should be no boats left
    Examples:
      | width | height | matrix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 5     | 5      | "boat,boat,boat,water,water/boat,boat,water,water,water/boat,water,water,water,water/water,water,water,water,water/water,water,water,water,water"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 10    | 10     | "boat,boat,boat,boat,boat,water,water,water,water,water/boat,boat,boat,boat,boat,water,water,water,water,water/boat,boat,boat,boat,water,water,water,water,water,water/boat,boat,water,water,water,water,water,water,water,water/boat,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | 15    | 15     | "boat,boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water,water,water/boat,boat,boat,boat,water,water,water,water,water,water,water,water,water,water,water/boat,boat,boat,water,water,water,water,water,water,water,water,water,water,water,water/boat,boat,water,water,water,water,water,water,water,water,water,water,water,water,water/boat,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water" |