Feature: player mounts the board with his boats

  As a player
  I want to place my boats on a board
  So that I will be ready to begin a new match

  Scenario: mount the board
    Given I have a board with dimensions <width> x <height>
    And I have a set of boats for that board
    When I place each boat side by side from the biggest to the smallest, beginning from the top-left
    Then my private board should be: <matrix>
    And there should be no boats left
    Examples:
      | width | height | matrix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | 5     | 5      | "boat,boat,boat,water,water/boat,boat,water,water,water/boat,water,water,water,water/water,water,water,water,water/water,water,water,water,water"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 10    | 10     | "boat,boat,boat,boat,boat,water,water,water,water,water/boat,boat,boat,boat,boat,water,water,water,water,water/boat,boat,boat,boat,water,water,water,water,water,water/boat,boat,water,water,water,water,water,water,water,water/boat,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | 15    | 15     | "boat,boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water,water/boat,boat,boat,boat,boat,boat,water,water,water,water,water,water,water,water,water/boat,boat,boat,boat,water,water,water,water,water,water,water,water,water,water,water/boat,boat,boat,water,water,water,water,water,water,water,water,water,water,water,water/boat,boat,water,water,water,water,water,water,water,water,water,water,water,water,water/boat,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water/water,water,water,water,water,water,water,water,water,water,water,water,water,water,water" |

  Scenario: boat overlapping
    Given I have a board with dimensions 2 x 3
    And I have a boat with size 2
    And I have another boat with size 2
    And I have already placed the first boat
    When I try to place the next boat overlapping at least one of the cells of the first boat
    Then I should be informed about the problem with a feedback about the overlapping cells
    And the board should not change
    And the boat should not be placed
